### ISSUE TITLE
Passing keep_alive

### ISSUE THREAD

**Issue by Jamonek** [cloudstudio/ollama-laravel#11]
I have searched through the source code with no luck on figuring out how to pass `keep_alive`. Am I missing something here?

**Comment by cloudstudio** [comment]
Hello @Jamonek, I can add this. It is not in the package for now.

**Comment by Jamonek** [comment]
Nice!! Thank you. I cloned the repo yesterday to submit a PR with keep alive available. I'll wait for you

**Comment by cloudstudio** [comment]
Sure! If you want to implement it, @Jamonek , feel free. It's a couple of lines of code! Happy to merge your PR.

**Comment by Jamonek** [comment]
Opened up the PR - #12
