### ISSUE TITLE
Ability to use API key

### ISSUE THREAD

**Issue by plabbett** [cloudstudio/ollama-laravel#13]
The underlying llama.cpp has an `--api-key` option that I would like to utilize, but Ollama does not support. Their current recommendation appears to be setup your own proxy - which is fine - but I need to be able to pass the api key in the Guzzle request regardless if they support llama.cpp's option or my own proxy. 

Is this something that makes sense to do a pull request for? I'm thinking a new .env variable and config key allowing the authorization header via Guzzle: `Authorization: Bearer <apikey>` added to [https://github.com/cloudstudio/ollama-laravel/blob/main/src/Traits/MakesHttpRequests.php](https://github.com/cloudstudio/ollama-laravel/blob/main/src/Traits/MakesHttpRequests.php)?

- [https://github.com/ollama/ollama/issues/849](https://github.com/ollama/ollama/issues/849)
- [https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md)

**Comment by cloudstudio** [comment]
Hey @plabbett,

I don't see why not, it's probably not something that is usually used, but if we put it as an optional parameter I don't see the problem.

If you want to make a PR, I will be happy to merge it!
