### ISSUE TITLE
Example to use Embeddings?

### ISSUE THREAD

**Issue by davitlee88** [cloudstudio/ollama-laravel#15]
thanks a lot for the package help me done so many things in my project, can you help to add more example to use Embeddings?

**Comment by cloudstudio** [comment]
Hey @davitlee88! This package is only a wrapper for Ollama. I think for these questions you need to move [there](https://github.com/ollama/ollama/issues). In the end, you need to use LangChain, Python, etc., to make this work. With this package or Ollama, you can just create embeds, but you need to work with other technologies to get it to work.
