### ISSUE TITLE
All responses are returning null

### ISSUE THREAD

**Issue by MDaskalovAtBE** [cloudstudio/ollama-laravel#17]
When I try to run just the default it returns null

```
        dd(\Cloudstudio\Ollama\Facades\Ollama::agent('You are a weather expert...')
            ->prompt('Why is the sky blue?')
            ->model('llama3')
            ->keepAlive('10m')
            ->options(['temperature' => 0.8])
            ->stream(false)
            ->ask());
```

It appears that `OLLAMA_URL=http://ollama.test/` inside my .env gives enough information for the requests to proceed but the end result is not working. To fix it just remove the ending "/" so it will become - `OLLAMA_URL=http://ollama.test`

It could be fixed as a small amend on the code but there is still an easy fix with amending the url.

Hope that helps someone in the future.

**Comment by LebToki** [comment]
Thanks for the efforts 👌
