### ISSUE TITLE
Messages

### ISSUE THREAD

**Issue by mralston** [cloudstudio/ollama-laravel#2]
Would it be possible to add support for the messages parameter in order to maintain history when creating a chatbot integration?

https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-a-chat-completion

**Comment by cloudstudio** [comment]
Hey this is new! let me check it

**Comment by cloudstudio** [comment]
@mralston check it in last release

Example of use: 

`$messages = [
    ['role' => 'user', 'content' => 'My name is Toni Soriano and I live in Spain'],
    ['role' => 'assistant', 'content' => 'Nice to meet you , Toni Soriano'],
    ['role' => 'user', 'content' => 'where I live ?'],
];

$response = Ollama::agent('You know me really well!')
    ->model('llama2')
    ->chat($messages);

// "You mentioned that you live in Spain."`

**Comment by mralston** [comment]
Oh, fantastic! That was a very quick turnaround.

I'll give a go. I've got the history stored in a database in my project, so populating the messages array will be trivial.

I agree that keeping it a wrapper is the right way to go. You could potentially create a separate project which pulled this on in as a dependency. That project could implement the database integration, etc. It could serve as a useful demo project to show people how to use this package.

**Comment by cloudstudio** [comment]
Yes! probably when Ollama have vision ready (I don't think it will take long) I will make a demo project with a chat GPT clone with vision etc, using Laravel and Livewire.

It seems to work well, let me know with your data how it went!

**Comment by mralston** [comment]
Works a treat! 😀

**Comment by marianoarga** [comment]
Related to this, how could I consumen the stream? since this request responds with an array and not a resource (having "stream" true by default)
