### ISSUE TITLE
Stream chat

### ISSUE THREAD

**Issue by marianoarga** [cloudstudio/ollama-laravel#4]
Hello, how could I consumen the chat or any stream? since this request responds with an array and not a resource (having "stream" true by default)

```
$response = Ollama::agent("You are an awesome assistant")
  ->model('llama2')
  ->stream(true)
  ->chat($this->conversation);
                
  dd($response)
               
  (returns array)
```

**Comment by marianoarga** [comment]
It seemed there was no streamed responses from API, I created MR for this, thank you

https://github.com/cloudstudio/ollama-laravel/pull/5

**Comment by marianoarga** [comment]
Closed issue by mistake, please close once merged, thx

**Comment by cloudstudio** [comment]
@marianoarga merged, thanks
